# Generated by Django 5.2.7 on 2026-02-07 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Desserts', 'Desserts'), ('Savory Snacks', 'Savory Snacks'), ('Coffee Beans', 'Coffee Beans'), ('Merchandise', 'Merchandise')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='menu_menuit_categor_a80b8d_idx'), models.Index(fields=['is_active'], name='menu_menuit_is_acti_c9fc39_idx')],
            },
        ),
    ]
