# Generated by Django 5.2.7 on 2026-02-07 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('item_specific', 'Item Specific')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specific_items', models.ManyToManyField(blank=True, related_name='discounts', to='menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
            ],
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='discounts_d_code_3a970a_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active'], name='discounts_d_is_acti_ae32b7_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['valid_from', 'valid_to'], name='discounts_d_valid_f_c17041_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerdiscountusage',
            unique_together={('user', 'discount')},
        ),
    ]
