# Generated by Django 5.2.7 on 2025-11-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Desserts', 'Desserts'), ('Savory Snacks', 'Savory Snacks'), ('Coffee Beans', 'Coffee Beans'), ('Merchandise', 'Merchandise')], max_length=50)),
            ],
        ),
    ]
